language: php
php:
  - 5.6
  - 7.2

dist: xenial
addons:
  apt:
    packages:
      - openjdk-8-jdk

before_install:
  - sudo apt-get update > /dev/null

install:
  # install gremlin-server
  - sh -c ./build/server/install.sh
  # set and install composer dependencies
  - if [ -n "$GH_TOKEN" ]; then composer config --global github-oauth.github.com ${GH_TOKEN}; else echo "no token"; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]] || [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then composer update -v; else composer install -v; fi

script: if [[ ${GRAPHSON_VERSION} == "3.0" ]]; then vendor/bin/phpunit --configuration build/phpunit.xml --testsuit graphson3; else vendor/bin/phpunit --configuration build/phpunit.xml --testsuit graphson1; fi

after_success:
  - sh -c ./build/deploy.sh

env:
  matrix:
    - GREMLINSERVER_VERSION="3.2.11" GRAPHSON_VERSION="1.0"
    - GREMLINSERVER_VERSION="3.3.11" GRAPHSON_VERSION="1.0"
    - GREMLINSERVER_VERSION="3.3.11" GRAPHSON_VERSION="3.0"
    - GREMLINSERVER_VERSION="3.4.8" GRAPHSON_VERSION="1.0"
    - GREMLINSERVER_VERSION="3.4.8" GRAPHSON_VERSION="3.0"

deploy:
  provider: pages
  repo: PommeVerte/PommeVerte.github.io
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: ./build/logs/PommeVerte.github.io
  target-branch: master
  verbose: true
  project-name: PommeVerte/gremlin-php
  on:
    branch: master
    condition: $TRAVIS_PHP_VERSION = "5.6" && $GRAPHSON_VERSION = "3.0"
